services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=registry
      - POSTGRES_USER=registry
      - POSTGRES_DB=registry
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
  registry:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile
    command: "server"
    env_file: .env
    ports:
      - 8081:8081
  workers:
    depends_on:
      - postgres
      - registry
    build:
      dockerfile: Dockerfile
    command: "workers"
    env_file: .env

volumes:
  db-data: