// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BlobChunksColumns holds the columns for the "blob_chunks" table.
	BlobChunksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "upload_id", Type: field.TypeString},
		{Name: "session_id", Type: field.TypeString},
		{Name: "range_from", Type: field.TypeUint64},
		{Name: "range_to", Type: field.TypeUint64},
		{Name: "part_number", Type: field.TypeUint64},
	}
	// BlobChunksTable holds the schema information for the "blob_chunks" table.
	BlobChunksTable = &schema.Table{
		Name:       "blob_chunks",
		Columns:    BlobChunksColumns,
		PrimaryKey: []*schema.Column{BlobChunksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "blobchunk_upload_id",
				Unique:  true,
				Columns: []*schema.Column{BlobChunksColumns[1]},
			},
			{
				Name:    "blobchunk_session_id",
				Unique:  true,
				Columns: []*schema.Column{BlobChunksColumns[2]},
			},
		},
	}
	// ManifestsColumns holds the columns for the "manifests" table.
	ManifestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "media_type", Type: field.TypeString},
		{Name: "s3_path", Type: field.TypeString},
		{Name: "digest", Type: field.TypeString},
		{Name: "repository_manifests", Type: field.TypeInt, Nullable: true},
	}
	// ManifestsTable holds the schema information for the "manifests" table.
	ManifestsTable = &schema.Table{
		Name:       "manifests",
		Columns:    ManifestsColumns,
		PrimaryKey: []*schema.Column{ManifestsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "manifests_repositories_manifests",
				Columns:    []*schema.Column{ManifestsColumns[4]},
				RefColumns: []*schema.Column{RepositoriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ManifestTagReferencesColumns holds the columns for the "manifest_tag_references" table.
	ManifestTagReferencesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "tag", Type: field.TypeString},
		{Name: "manifest_tag_reference_manifests", Type: field.TypeInt, Nullable: true},
	}
	// ManifestTagReferencesTable holds the schema information for the "manifest_tag_references" table.
	ManifestTagReferencesTable = &schema.Table{
		Name:       "manifest_tag_references",
		Columns:    ManifestTagReferencesColumns,
		PrimaryKey: []*schema.Column{ManifestTagReferencesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "manifest_tag_references_manifests_manifests",
				Columns:    []*schema.Column{ManifestTagReferencesColumns[2]},
				RefColumns: []*schema.Column{ManifestsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// RepositoriesColumns holds the columns for the "repositories" table.
	RepositoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// RepositoriesTable holds the schema information for the "repositories" table.
	RepositoriesTable = &schema.Table{
		Name:       "repositories",
		Columns:    RepositoriesColumns,
		PrimaryKey: []*schema.Column{RepositoriesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BlobChunksTable,
		ManifestsTable,
		ManifestTagReferencesTable,
		RepositoriesTable,
	}
)

func init() {
	ManifestsTable.ForeignKeys[0].RefTable = RepositoriesTable
	ManifestTagReferencesTable.ForeignKeys[0].RefTable = ManifestsTable
}
