-- Create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "given_name" character varying NOT NULL, "family_name" character varying NOT NULL, "email" character varying NOT NULL, "sub" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create index "user_email" to table: "users"
CREATE UNIQUE INDEX "user_email" ON "users" ("email");
-- Create index "user_sub" to table: "users"
CREATE UNIQUE INDEX "user_sub" ON "users" ("sub");
