// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/estebangarcia/cm3070-final-project/pkg/repositories/ent/organization"
	"github.com/estebangarcia/cm3070-final-project/pkg/repositories/ent/organizationmembership"
	"github.com/estebangarcia/cm3070-final-project/pkg/repositories/ent/user"
)

// OrganizationMembership is the model entity for the OrganizationMembership schema.
type OrganizationMembership struct {
	config `json:"-"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID int `json:"organization_id,omitempty"`
	// Role holds the value of the "role" field.
	Role int `json:"role,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OrganizationMembershipQuery when eager-loading is set.
	Edges        OrganizationMembershipEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OrganizationMembershipEdges holds the relations/edges for other nodes in the graph.
type OrganizationMembershipEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Organization holds the value of the organization edge.
	Organization *Organization `json:"organization,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrganizationMembershipEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// OrganizationOrErr returns the Organization value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrganizationMembershipEdges) OrganizationOrErr() (*Organization, error) {
	if e.Organization != nil {
		return e.Organization, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: organization.Label}
	}
	return nil, &NotLoadedError{edge: "organization"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OrganizationMembership) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case organizationmembership.FieldUserID, organizationmembership.FieldOrganizationID, organizationmembership.FieldRole:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OrganizationMembership fields.
func (om *OrganizationMembership) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case organizationmembership.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				om.UserID = int(value.Int64)
			}
		case organizationmembership.FieldOrganizationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value.Valid {
				om.OrganizationID = int(value.Int64)
			}
		case organizationmembership.FieldRole:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				om.Role = int(value.Int64)
			}
		default:
			om.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OrganizationMembership.
// This includes values selected through modifiers, order, etc.
func (om *OrganizationMembership) Value(name string) (ent.Value, error) {
	return om.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the OrganizationMembership entity.
func (om *OrganizationMembership) QueryUser() *UserQuery {
	return NewOrganizationMembershipClient(om.config).QueryUser(om)
}

// QueryOrganization queries the "organization" edge of the OrganizationMembership entity.
func (om *OrganizationMembership) QueryOrganization() *OrganizationQuery {
	return NewOrganizationMembershipClient(om.config).QueryOrganization(om)
}

// Update returns a builder for updating this OrganizationMembership.
// Note that you need to call OrganizationMembership.Unwrap() before calling this method if this OrganizationMembership
// was returned from a transaction, and the transaction was committed or rolled back.
func (om *OrganizationMembership) Update() *OrganizationMembershipUpdateOne {
	return NewOrganizationMembershipClient(om.config).UpdateOne(om)
}

// Unwrap unwraps the OrganizationMembership entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (om *OrganizationMembership) Unwrap() *OrganizationMembership {
	_tx, ok := om.config.driver.(*txDriver)
	if !ok {
		panic("ent: OrganizationMembership is not a transactional entity")
	}
	om.config.driver = _tx.drv
	return om
}

// String implements the fmt.Stringer.
func (om *OrganizationMembership) String() string {
	var builder strings.Builder
	builder.WriteString("OrganizationMembership(")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", om.UserID))
	builder.WriteString(", ")
	builder.WriteString("organization_id=")
	builder.WriteString(fmt.Sprintf("%v", om.OrganizationID))
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(fmt.Sprintf("%v", om.Role))
	builder.WriteByte(')')
	return builder.String()
}

// OrganizationMemberships is a parsable slice of OrganizationMembership.
type OrganizationMemberships []*OrganizationMembership
